# Copyright 2026 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
import sys

from google.adk.agents import Agent
from google.adk.apps import App
from google.adk.models import Gemini
from google.adk.tools.mcp_tool import McpToolset
from google.adk.tools.mcp_tool.mcp_session_manager import StdioConnectionParams
from google.genai import types
from mcp import StdioServerParameters

from app.tools.market_metrics import get_stock_quote, get_technical_indicators
from mcp_servers.rss_server import (
    get_alphabet_ir_updates,
    get_alphabet_news_headlines,
)

MODEL = "gemini-3.8-flash"

DISCLAIMER_TEXT = (
    "\n\n---\n"
    "**Disclaimer:** *This analysis is generated by an AI assistant for informational "
    "and educational purposes only. It does not constitute financial, investment, "
    "legal, or trading advice. Always conduct independent research and consult a "
    "licensed financial advisor before making investment decisions.*"
)

# ---------------------------------------------------------------------------
# 1. MCP Toolset for RSS News Feeds
# ---------------------------------------------------------------------------
server_script = os.path.abspath(
    os.path.join(os.path.dirname(__file__), "..", "mcp_servers", "rss_server.py")
)

try:
    rss_mcp_toolset = McpToolset(
        connection_params=StdioConnectionParams(
            server_params=StdioServerParameters(
                command=sys.executable,
                args=[server_script],
            )
        )
    )
    news_tools = [rss_mcp_toolset]
except Exception:
    # Fallback to direct python tools if subprocess IPC is restricted
    news_tools = [get_alphabet_news_headlines, get_alphabet_ir_updates]


# ---------------------------------------------------------------------------
# 2. Specialist Sub-Agent: Market Metrics (Yahoo Finance)
# ---------------------------------------------------------------------------
MARKET_METRICS_INSTRUCTION = """You are the Market Metrics Specialist for Alphabet Inc. (GOOG / GOOGL).
Your sole focus is retrieving accurate, real-time and historical quantitative market data.

Guidelines:
1. When asked for quotes, prices, trading volumes, or day ranges, invoke `get_stock_quote`.
2. When asked for moving averages (SMA 50, SMA 200), trend directions, RSI (14-day), or technical momentum, invoke `get_technical_indicators`.
3. Never invent, estimate, or hallucinate financial numbers. Ground every figure strictly in the tool outputs.
4. Present numbers with clear units (e.g. USD, percentages, dates).
5. If an unsupported ticker is requested, state clearly that you specialize exclusively in Alphabet Inc. (GOOG/GOOGL).
"""

market_metrics_agent = Agent(
    name="market_metrics_agent",
    model=Gemini(
        model=MODEL,
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    description=(
        "Specialist sub-agent for querying real-time market quotes, prices, volume, "
        "and calculating technical indicators (50-day SMA, 200-day SMA, RSI 14) for Alphabet Inc. (GOOG/GOOGL)."
    ),
    instruction=MARKET_METRICS_INSTRUCTION,
    tools=[get_stock_quote, get_technical_indicators],
)


# ---------------------------------------------------------------------------
# 3. Specialist Sub-Agent: News & Sentiment (MCP RSS Aggregator)
# ---------------------------------------------------------------------------
NEWS_SENTIMENT_INSTRUCTION = """You are the News & Sentiment Intelligence Specialist for Alphabet Inc. (Google).
Your sole focus is gathering and summarizing recent public RSS news feeds and official corporate announcements.

Guidelines:
1. Invoke the available news tools to pull recent headlines and official Google Blog / IR updates.
2. Group stories into clear themes (e.g., Cloud & AI, Search & Ads, Regulatory & Legal, Corporate).
3. Provide concise, bulleted executive summaries highlighting the potential business impact.
4. Always cite headline titles and dates when available.
5. If no news is found or tools report network warnings, explain the status transparently without making up stories.
"""

news_sentiment_agent = Agent(
    name="news_sentiment_agent",
    model=Gemini(
        model=MODEL,
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    description=(
        "Specialist sub-agent for fetching, filtering, and summarizing recent public news headlines "
        "and official corporate press releases regarding Alphabet Inc. and Google via RSS/MCP."
    ),
    instruction=NEWS_SENTIMENT_INSTRUCTION,
    tools=news_tools,
)


# ---------------------------------------------------------------------------
# 4. Root Coordinator Agent: StockCoordinatorAgent
# ---------------------------------------------------------------------------
COORDINATOR_INSTRUCTION = f"""You are the Lead Financial Intelligence Coordinator specializing in Alphabet Inc. (Google, tickers GOOG and GOOGL).
You assist investors, researchers, and professionals by combining quantitative technical indicators with qualitative news sentiment.

Your Responsibilities:
1. **Analyze User Intent**:
   - For pure stock prices, quotes, moving averages, or RSI: Delegate to `market_metrics_agent`.
   - For news, headlines, corporate statements, or sentiment: Delegate to `news_sentiment_agent`.
   - For comprehensive briefings or predictions: Coordinate with BOTH sub-agents and synthesize their findings into a cohesive, structured analysis.

2. **Synthesis Structure (when providing full briefings or outlooks)**:
   - **Executive Summary**: 2-3 sentence overview of current posture.
   - **Market Metrics & Technicals**: Current price, 50-day / 200-day moving average positioning (e.g. Golden/Death cross), RSI momentum state.
   - **Key News Developments**: Top 3-5 summarized news events categorized by theme.
   - **Analytical Outlook / Scenarios**: Balanced scenario outlook (Bull case vs. Bear case based on the indicators and news).

3. **Mandatory Safety Rule**:
   Every response that provides an analytical overview, trend assessment, or prediction MUST conclude with the following exact disclaimer:
   "{DISCLAIMER_TEXT}"

4. **Scope Restriction**:
   You specialize exclusively in Alphabet Inc. (GOOG / GOOGL). If a user asks about an unrelated company or stock, politely decline and offer to analyze Alphabet instead.
"""

root_agent = Agent(
    name="my_agent_l200",
    model=Gemini(
        model=MODEL,
        retry_options=types.HttpRetryOptions(attempts=3),
    ),
    instruction=COORDINATOR_INSTRUCTION,
    sub_agents=[market_metrics_agent, news_sentiment_agent],
)

app = App(
    root_agent=root_agent,
    name="app",
)
